target 'StockMasterSDKUpdate' do
	pod 'FMDB'
	pod 'SAMKeychain'
	pod 'SDWebImage', '~> 3.8'
	pod 'TTTAttributedLabel'
    pod 'Mosquitto'
	pod 'XlsxReaderWriter'
	pod 'hpple'
	pod 'AWSS3'
	pod 'AWSAPIGateway'
	pod 'Fabric'
	pod 'TwitterCore', '~> 2.8'
	pod 'TwitterKit', '~> 2.8'
	pod 'Crashlytics'
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/AdMob'
	pod 'Firebase/Messaging'
	pod 'Firebase/RemoteConfig'
	pod 'Firebase/Invites'
	pod 'AWSSNS'
	pod 'AWSMobileAnalytics'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'JSQMessagesViewController'
	pod 'MWPhotoBrowser'

	source 'https://github.com/CocoaPods/Specs.git'
end
